import * as PenpaPlayer from "./player"

customElements.define('slitherlink-player', PenpaPlayer.SlitherlinkPlayer);
customElements.define("mashu-player", PenpaPlayer.MashuPlayer)
customElements.define("sudoku-player", PenpaPlayer.SudokuPlayer)
customElements.define("kakkuro-player", PenpaPlayer.KakkuroPlayer)
customElements.define("numberlink-player", PenpaPlayer.NumberlinkPlayer)
customElements.define("nurikabe-player", PenpaPlayer.NurikabePlayer)
customElements.define("fillomino-player", PenpaPlayer.FillominoPlayer)
customElements.define("hitokure-player", PenpaPlayer.HitokurePlayer)
customElements.define("shakashaka-player", PenpaPlayer.ShakashakaPlayer)
customElements.define("shikaku-player", PenpaPlayer.ShikakuPlayer)
customElements.define("heyawake-player", PenpaPlayer.HeyawakePlayer)
customElements.define("yajilin-player", PenpaPlayer.YajilinPlayer)
customElements.define("ripple-player", PenpaPlayer.RipplePlayer)
customElements.define("tentaisho-player", PenpaPlayer.TentaishoPlayer)
customElements.define("norinori-player", PenpaPlayer.NorinoriPlayer)
customElements.define("lits-player", PenpaPlayer.LitsPlayer)
customElements.define("akari-player", PenpaPlayer.AkariPlayer)
customElements.define("tilepaint-player", PenpaPlayer.TilePaintPlayer)
customElements.define("nurimaze-player", PenpaPlayer.NurimazePlayer)